import Navigation from '@/components/common/navigation'
import './globals.css'
import ChakraProviders from './providers/chakra-providers'
import Footer from '@/components/common/footer'

export const metadata = {
  title: 'Ionic Formula Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProviders>
          <Navigation />
          {children}
          <Footer />
        </ChakraProviders>
      </body>
    </html>
  )
}
